const COUNTRY_LIST = [
    "Burundi",
    "Benin",
    "Bhutan",
    "Belize",
    "Central African Republic",
    "Republic of Congo",
    "Djibouti",
    "Western Sahara",
    "Eritrea",
    "Falkland Islands",
    "Fiji",
    "French Guiana",
    "Greenland",
    "Gambia",
    "Guinea-Bissau",
    "Guyana",
    "Haiti",
    "Kyrgyzstan",
    "North Korea",
    "Kosovo",
    "Liberia",
    "Lesotho",
    "Montenegro",
    "Mauritania",
    "Malawi",
    "New Caledonia",
    "Niger",
    "Nicaragua",
    "Rwanda",
    "Solomon Islands",
    "Svalbard and Jan Mayen",
    "Sierra Leone",
    "Somalia",
    "Suriname",
    "South Sudan",
    "Swaziland",
    "Chad",
    "French Southern and Antarctic Lands",
    "Togo",
    "Tajikistan",
    "Timor-Leste",
    "Vanuatu",
    "United Arab Emirates",
    "Afghanistan",
    "Albania",
    "Armenia",
    "Angola",
    "Argentina",
    "Austria",
    "Australia",
    "Azerbaijan",
    "Bosnia and Herzegovina",
    "Bangladesh",
    "Belgium",
    "Burkina Faso",
    "Bulgaria",
    "Brunei Darussalam",
    "Bolivia",
    "Brazil",
    "Bahamas",
    "Botswana",
    "Belarus",
    "Canada",
    "Democratic Republic of Congo",
    "Switzerland",
    "Côte d'Ivoire",
    "Chile",
    "Cameroon",
    "China",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Cyprus",
    "Czechia",
    "Germany",
    "Denmark",
    "Dominican Republic",
    "Algeria",
    "Ecuador",
    "Estonia",
    "Egypt",
    "Spain",
    "Ethiopia",
    "Finland",
    "France",
    "Gabon",
    "United Kingdom",
    "Georgia",
    "Ghana",
    "Guinea",
    "Equatorial Guinea",
    "Greece",
    "Guatemala",
    "Honduras",
    "Croatia",
    "Hungary",
    "Indonesia",
    "Ireland",
    "Israel",
    "India",
    "Iraq",
    "Iran",
    "Iceland",
    "Italy",
    "Jamaica",
    "Jordan",
    "Japan",
    "Kenya",
    "Cambodia",
    "South Korea",
    "Kuwait",
    "Kazakhstan",
    "Lao People's Democratic Republic",
    "Lebanon",
    "Sri Lanka",
    "Lithuania",
    "Luxembourg",
    "Latvia",
    "Libya",
    "Morocco",
    "Moldova",
    "Madagascar",
    "Macedonia",
    "Mali",
    "Myanmar",
    "Mongolia",
    "Mexico",
    "Malaysia",
    "Mozambique",
    "Namibia",
    "Nigeria",
    "Netherlands",
    "Norway",
    "Nepal",
    "New Zealand",
    "Oman",
    "Panama",
    "Peru",
    "Papua New Guinea",
    "Philippines",
    "Poland",
    "Pakistan",
    "Puerto Rico",
    "Palestinian Territories",
    "Portugal",
    "Paraguay",
    "Qatar",
    "Romania",
    "Serbia",
    "Russia",
    "Saudi Arabia",
    "Sudan",
    "Sweden",
    "Slovenia",
    "Slovakia",
    "Senegal",
    "El Salvador",
    "Syria",
    "Thailand",
    "Turkmenistan",
    "Tunisia",
    "Turkey",
    "Trinidad and Tobago",
    "Taiwan",
    "Tanzania",
    "Ukraine",
    "Uganda",
    "United States",
    "Uruguay",
    "Uzbekistan",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "South Africa",
    "Zambia",
    "Zimbabwe",
]
module.exports = COUNTRY_LIST;